[build]
publish = "src/"
functions = "functions/"

# [[redirects]]
# from = "/:splat"
# to = "https://kirbodev.com/:splat"
# status = 200
# force = true

[[redirects]]
from = "/view/*"
to = "/.netlify/functions/view/:splat"

[[redirects]]
from = "/dog/*"
to = "/.netlify/functions/dog/:splat"

[[redirects]]
from = "/cat/*"
to = "/.netlify/functions/cat/:splat"

[[redirects]]
from = "/deepfry/*"
to = "/.netlify/functions/deepfry/:splat"

[[redirects]]
from = "/what/*"
to = "/.netlify/functions/what/:splat"

[[redirects]]
from = "/caption/*"
to = "/.netlify/functions/caption/:splat"

[[redirects]]
from = "/meme/*"
to = "/.netlify/functions/meme/:splat"

[[redirects]]
from = "/pe/*"
to = "/.netlify/functions/pe/:splat"

[[redirects]]
from = "/blurple/*"
to = "/.netlify/functions/blurple/:splat"

[[redirects]]
from = "/trash/*"
to = "/.netlify/functions/trash/:splat"

[[headers]]
for = "/deepfry/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/view/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/what/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/pe/*"
[headers.values]
Cache-Control = "public, max-age=86400"