[build]
publish = "src/"
functions = "functions/"

# [[redirects]]
# from = "/:splat"
# to = "https://kirbodev.com/:splat"
# status = 200
# force = true

[[redirects]]
from = "/view/:splat"
to = "/.netlify/functions/view/:splat"

[[redirects]]
from = "/dog/:splat"
to = "/.netlify/functions/dog/:splat"

[[redirects]]
from = "/cat/:splat"
to = "/.netlify/functions/cat/:splat"

[[redirects]]
from = "/deepfry/:splat"
to = "/.netlify/functions/deepfry/:splat"

[[redirects]]
from = "/what/:splat"
to = "/.netlify/functions/what/:splat"

[[redirects]]
from = "/caption/:splat/:id"
to = "/.netlify/functions/caption/:splat/:id"

[[redirects]]
from = "/caption/:splat"
to = "/.netlify/functions/caption/:splat"

[[redirects]]
from = "/meme/:splat"
to = "/.netlify/functions/meme/:splat"

[[redirects]]
from = "/pe/:splat"
to = "/.netlify/functions/pe/:splat"

[[redirects]]
from = "https://media.tencuter.com/*"
to = "https://tencuter.com/*"
force = true

[[headers]]
for = "/deepfry/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/view/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/what/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/pe/*"
[headers.values]
Cache-Control = "public, max-age=86400"